//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;
use crate::db::map::DecodeMap;
use crate::Id;
use crate::time::Timestamp;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "snap_decode_script")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: Id,
    #[sea_orm(column_type = "Text")]
    pub script: String,
    #[sea_orm(column_type = "Text")]
    pub lang: String,
    pub owner: Id,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    pub map: DecodeMap,
    pub create_time: Timestamp,
    pub modify_time: Timestamp,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
