FROM nginx:stable-alpine AS nginx
WORKDIR /usr/share/nginx/html

COPY snapemu-web/dist /usr/share/nginx/html
COPY docker/snapemu.conf /etc/nginx/conf.d/default.conf
ENTRYPOINT ["/docker-entrypoint.sh"]

EXPOSE 80

STOPSIGNAL SIGQUIT

CMD ["nginx", "-g", "daemon off;"]