name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install gcc
      run: sudo apt-get install gcc-aarch64-linux-gnu
    - name: Install target
      run: rustup target add aarch64-unknown-linux-gnu
    - name: Build
      run: cargo build  --target=aarch64-unknown-linux-gnu  --verbose
    - name: Run tests
      run: cargo test --verbose
