name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc
  CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER: aarch64-linux-musl-gcc
  SNAPEMU_DEVICE_VERSION: v1
  SNAPEMU_API_VERSION: v1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install gcc
      run: sudo apt-get install gcc-aarch64-linux-gnu
    - name: Install target
      run: rustup target add aarch64-unknown-linux-musl
    - name: Cache
      uses: Swatinem/rust-cache@v2.7.5
    - name: Build 
      run: | 
        wget https://musl.cc/aarch64-linux-musl-cross.tgz
        tar xf aarch64-linux-musl-cross.tgz
        export PATH=$PWD/aarch64-linux-musl-cross/bin:$PATH
        cargo build  --target=aarch64-unknown-linux-musl --release
        mkdir bin/
        cp target/aarch64-unknown-linux-musl/release/snap_api bin/
    - name: 'Tar files'
      run: tar -Jcf bin.tar.xz bin
    - uses: actions/upload-artifact@v4
      with:
        name: bin-artifact
        path: bin.tar.xz
    - name: Display structure of downloaded files
      run: ls -R bin
