name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  release:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
    - id: assets
      name: assets
      run: |
        mkdir snapemu
        touch snapemu/1.tar.xz
        touch snapemu/2.tar.xz
        tmpstr='release={"files":['
        for file in snapemu/*.tar.xz; do
          tmpstr="${tmpstr}\"$file\","
        done
        tmpstr=${tmpstr%,}
        tmpstr="${tmpstr}]}"
        echo $tmpstr
        echo $tmpstr >> "$GITHUB_OUTPUT"
    - name: Release
      env:
        FILES: ${{ join(fromJSON(steps.assets.outputs.release).files, '\n') }}
      run: |
        echo $FILES
